[project]
name = "audio-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "mssql-python>=1.13.0",
    "openai>=2.50.0",
    "pydantic-settings>=2.15.0",
    "pydub>=0.25.1",
    "pymssql>=2.3.13",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
build = [
    "pyinstaller>=6.11.0",
]
