import os

LAST_ID_TESTIGO_FILE = os.environ.get(
    "TOOL2_LAST_ID_TESTIGO_FILE", "tool2_last_id_testigo.txt"
)
POLL_INTERVAL_SECONDS = int(
    os.environ.get("TOOL2_POLL_INTERVAL_SECONDS", float(60 * 60))
)
MAX_WORKERS = int(os.environ.get("TOOL2_MAX_WORKERS", 5))

ESTATUS_DESCARTADO_LOCUTOR: int = 10
ESTATUS_DESCARTADO_NOTICIERO: int = 11
ESTATUS_DESCARTADO_CANCION: int = 12
ESTATUS_DESCARTADO_INCONSISTENCIA: int = 13
ESTATUS_DESCARTADO_DURACION_MINIMA: int = 14
ESTATUS_DESCARTADO_GENERICO: int = 15
ESTATUS_DESCARTADO_AUDITORIA: int = 16
ESTATUS_DESCARTADO_NAC: int = 17
ESTATUS_DESCARTADO_ALTAS_AUTOMATICAS: int = 18
ESTATUS_DESCARTADO_REGLA: int = 21
TOOL2_ESTATUS_IDS: list[int] = [
    ESTATUS_DESCARTADO_LOCUTOR,
    ESTATUS_DESCARTADO_NOTICIERO,
    ESTATUS_DESCARTADO_CANCION,
    ESTATUS_DESCARTADO_INCONSISTENCIA,
    ESTATUS_DESCARTADO_DURACION_MINIMA,
    ESTATUS_DESCARTADO_GENERICO,
    ESTATUS_DESCARTADO_AUDITORIA,
    ESTATUS_DESCARTADO_NAC,
    ESTATUS_DESCARTADO_ALTAS_AUTOMATICAS,
    ESTATUS_DESCARTADO_REGLA,
]

TESTIGO_ESTATUS_TERMINADO: int = 10
TESTIGO_ESTATUS_BORRADO: int = 20
TOOL2_TESTIGO_ESTATUS_IDS: list[int] = [
    TESTIGO_ESTATUS_TERMINADO,
    TESTIGO_ESTATUS_BORRADO,
]
